#!/bin/sh -e

cd $(dirname $0)/..

source ./auto/set-env-vars

password="$( \
    docker run --rm \
        -v "${AWS_WEB_IDENTITY_TOKEN_FILE}":"${AWS_WEB_IDENTITY_TOKEN_FILE}" \
        -e AWS_ROLE_ARN \
        -e AWS_WEB_IDENTITY_TOKEN_FILE \
        -e AWS_REGION \
        amazon/aws-cli ecr get-login-password
)"

docker login \
    --password $password \
    --username AWS \
    "${ECR_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
